### ISSUE TITLE
There is a SyntaxError when I run your example code.

### ISSUE THREAD

**Issue by huang06** [tirthajyoti/pydbgen#1]
**code:**
testdf=myDB.gen_dataframe(25,fields='name','city','phone',
        'license_plate','email',real_email=True,phone_simple=True)

**SyntaxError:** positional argument follows keyword argument

**Comment by jchristensen912** [comment]
Make sure to have your fields placed in brackets since it is a list [ ]!!

**Comment by tirthajyoti** [comment]
Issue is closed after @jchristensen912's comment.
