### ISSUE TITLE
Data Generation Issue

### ISSUE THREAD

**Issue by AFNANAMIN** [tirthajyoti/pydbgen#17]
TypeError: Calling `.seed()` on instances is deprecated. Use the class method `Faker.seed()` instead.
I am getting this error when I am generating the data
![image](https://user-images.githubusercontent.com/33934146/94899340-8fe57e00-04ac-11eb-9e01-af605eac663d.png)

**Comment by loxosceles** [comment]
I'm having the same issue. Any updates on this?

**Comment by andypayne** [comment]
This is due to a breaking change in Faker [covered here](https://faker.readthedocs.io/en/master/fakerclass.html#breaking-change).

I've created PR #18 to fix this. Give it a try.

**Comment by mefryar** [comment]
Does anyone know how I could add the version of `pydbgen` that includes @andypayne's fix to a repository using `pipenv`?[PyPI lists the latest version of `pydbgen`](https://pypi.org/project/pydbgen/#history) as being from March 11, 2018, which wouldn't include this fix.

I tried `pipenv install -e git+https://github.com/tirthajyoti/pydbgen.git#egg=pydbgen` but got this error:
```
Running command git clone -q https://github.com/tirthajyoti/pydbgen.git /Users/michael/.local/share/virtualenvs/da_pipeline-sewM7QTV/src/pydbgen
ERROR: Could not find a version that satisfies the requirement sqlite (from pydbgen)
ERROR: No matching distribution found for sqlite
```

**Comment by andypayne** [comment]
Hi Michael, the sqlite requirement is causing this error. I updated it to `pysqlite3` in my fork and the install with pipenv succeeds:

```shell
❯ pipenv install -e git+https://github.com/andypayne/pydbgen.git#egg=pydbgen
Creating a virtualenv for this project...
Pipfile: /Users/andy/src/python/pipenv_test2/Pipfile
Using /opt/anaconda3/bin/python3 (3.8.3) to create virtualenv...
⠋ Creating virtual environment...created virtual environment CPython3.8.3.final.0-64 in 645ms
  creator CPython3Posix(dest=/Users/andy/.local/share/virtualenvs/pipenv_test2-GoxKWCFd, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/andy/Library/Application Support/virtualenv)
    added seed packages: pip==21.0.1, setuptools==54.1.2, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/andy/.local/share/virtualenvs/pipenv_test2-GoxKWCFd
Creating a Pipfile for this project...
Installing -e git+https://github.com/andypayne/pydbgen.git#egg=pydbgen...
Adding pydbgen to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (0e2d46)!
Installing dependencies from Pipfile.lock (0e2d46)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

For python 2 this would need to be `pysqlite`. I can submit a PR if @tirthajyoti would like it, or if python 2 compatibility is needed, I can try modifying `setup.py` to support versions 2 and 3.

**Comment by mefryar** [comment]
Thank you, Andy! Using your fork worked for me.

**Comment by tirthajyoti** [comment]
Closing since the `Faker` issue was solved by a PR.
