### ISSUE TITLE
FileNotFoundError 'Domains.txt'

### ISSUE THREAD

**Issue by sujitdhamale** [tirthajyoti/pydbgen#6]
while generating datafram getting below error 

`testdf=myDB.gen_dataframe(25,fields=['name','city','phone','license_plate','email'],real_email=True,phone_simple=True)
`
**Error** 

>     fh = open(path)
> FileNotFoundError: [Errno 2] No such file or directory: 'Domains.txt'

**Comment by richardliu44** [comment]
I also meet this issue...

**Comment by richardliu44** [comment]
Found a workaround:
copy C:\Python36\Lib\site-packages\pydbgen\Domains.txt to the folder that the py file is placed.

**Comment by tirthajyoti** [comment]
Issue is closed after @richardliu44 's comment
